export const config = [
  {
    chat_id: '-1001880573200',
    coach_id: '1115502449',
    trains: [
      {
        day: 'вівторок',
        time: '19:00-21:00',
        max: '8',
        location: 'CET',
        is_forum: false,
        publish_day: 'понеділок',
      },
      {
        day: 'четверг',
        time: '19:00-21:00',
        max: '8',
        location: 'CET',
        is_forum: false,
        publish_day: 'середа',
      },
      {
        day: 'суббота',
        time: '19:00-21:00',
        max: '8',
        location: 'CET',
        is_forum: false,
        publish_day: 'пятниця',
      },
    ],
  },
  {
    chat_id: '-1001599114412',
    coach_id: '543191951',
    trains: [
      {
        day: 'вівторок',
        time: '18:00-21:00',
        max: '18',
        location: '232 школа, вул Йорданська, 4Г (ст.м. Почайна/Петрівка)',
        is_forum: true,
        publish_day: 'середа',
        topic_id: 4639,
      },
      {
        day: 'середа',
        time: '18:00-21:00',
        max: '18',
        location: '232 школа, вул Йорданська, 4Г (ст.м. Почайна/Петрівка)',
        is_forum: true,
        publish_day: 'четверг',
        topic_id: 4640,
      },
      {
        day: 'четверг',
        time: '18:00-21:00',
        max: '18',
        location: '232 школа, вул Йорданська, 4Г (ст.м. Почайна/Петрівка)',
        is_forum: true,
        publish_day: 'пятниця',
        topic_id: 4642,
      },
      {
        day: 'пятниця',
        time: '18:00-21:00',
        max: '18',
        location: '232 школа, вул Йорданська, 4Г (ст.м. Почайна/Петрівка)',
        is_forum: true,
        publish_day: 'суббота',
        topic_id: 4643,
      },
      {
        day: 'суббота',
        time: '18:00-21:00',
        max: '18',
        location: '232 школа, вул Йорданська, 4Г (ст.м. Почайна/Петрівка)',
        is_forum: true,
        publish_day: 'неділя',
        topic_id: 4644,
      },
    ],
  },
];
